name: Docker Image CI/CD

on:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: dr.big.wtf
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VITE_BASE_API_URL=${{ vars.VITE_BASE_API_URL }}
          push: true
          tags: dr.big.wtf/depotly-account:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: [self-hosted, linux, arm64]
    needs: build

    steps:
      - name: Make request to webhook
        env:
          DEPLOY_WEBHOOK: ${{ vars.DEPLOY_WEBHOOK }}
        run: curl -X POST $DEPLOY_WEBHOOK
